metaData:
  title: Finance Tool
window:
  login:
    component:
      topFrame:
        row: 0
        column: 0
        padx: 30
        pady: 30
      loginPhotoLabel:
        row: 0
        column: 0
      bottomFrame:
        row: 1
        column: 0
        padx: 0
        pady: 10
      loginEntry:
        row: 0
        column: 0
        padx: 0
        pady: 0
  main:
    xOffset: 400
    yOffset: 100
    component:
      canvas:
        width: 1300
        height: 600
  transactions:
    xOffset: 400
    yOffset: 100
    component:
      topFrame:
        row: 0
        column: 0
        padx: 0
        pady: 0
      searchEntry:
        padx: 0
        pady: 0
        ipadx: 0
        ipady: 0
